// <auto-generated />
using BeeFacts.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BeeFacts.Migrations
{
    [DbContext(typeof(BeeFactContext))]
    partial class BeeFactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BeeFacts.Models.BeeFact", b =>
                {
                    b.Property<int>("BeeFactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BeeFactId"));

                    b.Property<string>("Fact")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BeeFactId");

                    b.ToTable("BeeFact");
                });
#pragma warning restore 612, 618
        }
    }
}
